[repository]
owner = "brejoc"
name = "test"
updateInterval = 3600

[board]
plannedColumns  = ["Requested", "Planned", "Backlog"]
blockedColumns  = ["Blocked", "Waiting", "Blocked / Postponed"]
bugLabels       = ["bug"]
supportLabels   = ["L3", "L3 question"]

[database]
host     = "localhost"
port     = 5432
user     = "filtra"
password = "filtra"
dbname   = "filtra"
