[repository]
owner = "brejoc"
name = "test"
updateInterval = 3600
bugLabels       = ["bug"]
supportLabels   = ["L3", "L3 question"]

[boards]

  [test]
  plannedColumns  = ["Requested", "Planned"]
  blockedColumns  = ["Blocked / Postponed", "Waiting for Request"]

  [test2]
  plannedColumns  = ["Todo"]
  blockedColumns  = ["Blocked"]

[database]
host     = "localhost"
port     = 5432
user     = "filtra"
password = "filtra"
dbname   = "filtra"
