[repository]
owner = "brejoc"
name = "test"
updateInterval = 3600

[boards]
    [boards.test]
    name = "test"
    plannedColumns  = ["Requested", "Planned"]
    blockedColumns  = ["Blocked / Postponed", "Waiting for Request"]
    bugLabels       = ["bug"]
    supportLabels   = ["L3", "L3 question"]

    [boards.test2]
    name = "test2"
    plannedColumns  = ["Todo"]
    blockedColumns  = ["Blocked"]
    bugLabels       = ["bug"]
    supportLabels   = ["L3", "L3 question"]