version: '3'
services:

  filtra-exporter:
    image: brejoc/filtra
    build: .
    environment:
      - GITHUB_TOKEN=$GITHUB_TOKEN
    command: "-debug"
    ports:
        - '8080:8080'

  grafana:
    image: grafana/grafana:6.2.5
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
