version: '3'
services:

  prometheus:
    image: prom/prometheus:v2.10.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus_data:/prometheus
    ports:
      - '9090:9090'


  filtra-exporter:
    image: brejoc/filtra
    build: .
    environment:
      - GITHUB_TOKEN=$GITHUB_TOKEN
    ports:
        - '8080:8080'

  grafana:
    image: grafana/grafana:6.2.5
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"