[repository]
owner = "brejoc"
name = "test"
updateInterval = 3600
bugLabels       = ["bug"]
supportLabels   = ["L3", "L3 question"]

[boards]

  [boards.test]
  plannedColumns  = ["Requested", "Planned"]
  blockedColumns  = ["Blocked / Postponed", "Waiting for Request"]